Resources:
  bioetanolPrecios:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bioetanol-precios
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: periodo
          AttributeType: S  
        - AttributeName: bioetCanAzucar
          AttributeType: S
        - AttributeName: bioetMaiz
          AttributeType: S  
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1      
      GlobalSecondaryIndexes:
        - IndexName: periodo
          KeySchema:
            - AttributeName: periodo
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: bioetCanAzucar
          KeySchema:
            - AttributeName: bioetCanAzucar
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: bioetMaiz
          KeySchema:
            - AttributeName: bioetMaiz
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1                
        

  # bioetanolTotal:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: bioetanolTotal
  #     AttributeDefinitions:
  #       - AttributeName: id
  #         AttributeType: S
  #       - AttributeName: produccion
  #         AttributeType: N
  #       - AttributeName: ventasTotales
  #         AttributeType: N  
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #       - AttributeName: produccion
  #         KeyType: RANGE  
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1

  # bioetanolMaiz:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: bioetanolMaiz
  #     AttributeDefinitions:
  #       - AttributeName: id
  #         AttributeType: S
  #       - AttributeName: produccion
  #         AttributeType: N
  #       - AttributeName: ventasTotales
  #         AttributeType: N  
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #       - AttributeName: produccion
  #         KeyType: RANGE  
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1 

  # bioetanolCanAzucar:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: bioetanolCanAzucar
  #     AttributeDefinitions:
  #       - AttributeName: id
  #         AttributeType: S
  #       - AttributeName: produccion
  #         AttributeType: N
  #       - AttributeName: ventasTotales
  #         AttributeType: N  
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #       - AttributeName: produccion
  #         KeyType: RANGE
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1     

        