Resources:
#-- Start with bioetanolPrecios -- 
  bioetanolPrecios:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bioetanol-precios
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
        - AttributeName: periodo
          AttributeType: S  
        - AttributeName: bioetCanAzucar
          AttributeType: S
        - AttributeName: bioetMaiz
          AttributeType: S
        - AttributeName: region
          AttributeType: S
        - AttributeName: unidadMedida
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1      
      GlobalSecondaryIndexes:
        - IndexName: periodo
          KeySchema:
            - AttributeName: periodo
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: bioetCanAzucar
          KeySchema:
            - AttributeName: bioetCanAzucar
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: bioetMaiz
          KeySchema:
            - AttributeName: bioetMaiz
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: region
          KeySchema:
            - AttributeName: region
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: unidadMedida
          KeySchema:
            - AttributeName: unidadMedida
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
#-- End with bioetanolPrecios --         
#-- Start with bioetanolTotal -- 
  bioetanolTotal:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bioetanol-total
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
        - AttributeName: periodo
          AttributeType: S   
        - AttributeName: produccion
          AttributeType: S
        - AttributeName: ventasTotales
          AttributeType: S
        - AttributeName: capacidadInstalada
          AttributeType: S
        - AttributeName: eficienciaProduccion
          AttributeType: S
        - AttributeName: ubicacion
          AttributeType: S
        - AttributeName: estadoOperativo
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1 
      GlobalSecondaryIndexes:
        - IndexName: periodo
          KeySchema:
            - AttributeName: periodo
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: produccion
          KeySchema:
            - AttributeName: produccion
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: ventasTotales
          KeySchema:
            - AttributeName: ventasTotales
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: capacidadInstalada
          KeySchema:
            - AttributeName: capacidadInstalada
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: eficienciaProduccion
          KeySchema:
            - AttributeName: eficienciaProduccion
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: ubicacion
          KeySchema:
            - AttributeName: ubicacion
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: estadoOperativo
          KeySchema:
            - AttributeName: estadoOperativo
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
#-- End with bioetanolTotal --
#-- Start with bioetanolTipos --         
  bioetanolTipos:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bioetanol-tipos
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
        - AttributeName: tipo
          AttributeType: S     
        - AttributeName: periodo
          AttributeType: S   
        - AttributeName: produccion
          AttributeType: S
        - AttributeName: ventasTotales
          AttributeType: S  
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1 
      GlobalSecondaryIndexes:
        - IndexName: tipo
          KeySchema:
            - AttributeName: tipo
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: periodo
          KeySchema:
            - AttributeName: periodo
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1        
        - IndexName: produccion
          KeySchema:
            - AttributeName: produccion
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: ventasTotales
          KeySchema:
            - AttributeName: ventasTotales
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
#-- End with bioetanolTipos --             